// priority: 0

ServerEvents.tags('entity_type', event => {
  event.add('justdirethings:creature_catcher_deny', '/cataclysm/')
  event.add('justdirethings:no_ai_deny', '/cataclysm/')
  event.add('justdirethings:polymorphic_target_deny', '/cataclysm/')

  event.add('justdirethings:creature_catcher_deny', '/cobblemon/')
  event.add('justdirethings:no_ai_deny', '/cobblemon/')
  event.add('justdirethings:polymorphic_target_deny', '/cobblemon/')
})

ServerEvents.tags('block', event => {
  event.add('create:wrench_pickup', 'oritech:machine_core_1')
    event.add('create:wrench_pickup', 'oritech:machine_core_2')
      event.add('create:wrench_pickup', 'oritech:machine_core_3')
        event.add('create:wrench_pickup', 'oritech:machine_core_4')
          event.add('create:wrench_pickup', 'oritech:machine_core_5')
            event.add('create:wrench_pickup', 'oritech:machine_core_6')
              event.add('create:wrench_pickup', 'oritech:machine_core_7')
})

ServerEvents.tags('fluid', event => {
  event.add('c:refined_t2_fluid_source', 'justdirethings:refined_t2_fluid_source')
})

ServerEvents.tags('item', event => {
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:white_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:orange_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:magenta_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:light_blue_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:yellow_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:lime_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:pink_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:gray_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:light_gray_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:cyan_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:purple_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:blue_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:brown_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:green_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:red_brick_extra')
    event.add('cardboardedition:extra_bricks', 'domum_ornamentum:black_brick_extra')

    event.add('cardboardedition:extra_cobblestone', 'domum_ornamentum:blue_cobblestone_extra')
    event.add('cardboardedition:extra_cobblestone', 'domum_ornamentum:green_cobblestone_extra')
    event.add('cardboardedition:extra_cobblestone', 'domum_ornamentum:mossy_cobblestone_extra')
    event.add('cardboardedition:extra_cobblestone', 'domum_ornamentum:purple_cobblestone_extra')
    event.add('cardboardedition:extra_cobblestone', 'domum_ornamentum:cobblestone_extra')

    event.add('cardboardedition:tera_shards', '/^mega_showdown:.*_shard$/')

    event.add('cardboardedition:sellable', 'cobblemon:azure_ball');
    event.add('cardboardedition:sellable', 'cobblemon:beast_ball');
    event.add('cardboardedition:sellable', 'cobblemon:cherish_ball');
    event.add('cardboardedition:sellable', 'cobblemon:citrine_ball');
    event.add('cardboardedition:sellable', 'cobblemon:dive_ball');
    event.add('cardboardedition:sellable', 'cobblemon:dream_ball');
    event.add('cardboardedition:sellable', 'cobblemon:dusk_ball');
    event.add('cardboardedition:sellable', 'cobblemon:fast_ball');
    event.add('cardboardedition:sellable', 'cobblemon:friend_ball');
    event.add('cardboardedition:sellable', 'cobblemon:great_ball');
    event.add('cardboardedition:sellable', 'cobblemon:heal_ball');
    event.add('cardboardedition:sellable', 'cobblemon:heavy_ball');
    event.add('cardboardedition:sellable', 'cobblemon:level_ball');
    event.add('cardboardedition:sellable', 'cobblemon:lure_ball');
    event.add('cardboardedition:sellable', 'cobblemon:love_ball');
    event.add('cardboardedition:sellable', 'cobblemon:luxury_ball');
    event.add('cardboardedition:sellable', 'cobblemon:moon_ball');
    event.add('cardboardedition:sellable', 'cobblemon:nest_ball');
    event.add('cardboardedition:sellable', 'cobblemon:net_ball');
    event.add('cardboardedition:sellable', 'cobblemon:park_ball');
    event.add('cardboardedition:sellable', 'cobblemon:poke_ball');
    event.add('cardboardedition:sellable', 'cobblemon:premier_ball');
    event.add('cardboardedition:sellable', 'cobblemon:quick_ball');
    event.add('cardboardedition:sellable', 'cobblemon:repeat_ball');
    event.add('cardboardedition:sellable', 'cobblemon:roseate_ball');
    event.add('cardboardedition:sellable', 'cobblemon:safari_ball');
    event.add('cardboardedition:sellable', 'cobblemon:slate_ball');
    event.add('cardboardedition:sellable', 'cobblemon:sport_ball');
    event.add('cardboardedition:sellable', 'cobblemon:timer_ball');
    event.add('cardboardedition:sellable', 'cobblemon:ultra_ball');
    event.add('cardboardedition:sellable', 'cobblemon:verdant_ball');

    event.add('cardboardedition:sellable', 'farmersdelight:beef_patty');
    event.add('cardboardedition:sellable', 'farmersdelight:cooked_chicken_cuts');
    event.add('cardboardedition:sellable', 'farmersdelight:cooked_bacon');
    event.add('cardboardedition:sellable', 'farmersdelight:cooked_cod_slice');
    event.add('cardboardedition:sellable', 'farmersdelight:cooked_salmon_slice');
    event.add('cardboardedition:sellable', 'farmersdelight:smoked_ham');
    event.add('cardboardedition:sellable', 'farmersdelight:cooked_mutton_chops');
    event.add('cardboardedition:sellable', 'farmersdelight:apple_pie');
    event.add('cardboardedition:sellable', 'farmersdelight:sweet_berry_cheesecake');
    event.add('cardboardedition:sellable', 'farmersdelight:chocolate_pie');
    event.add('cardboardedition:sellable', 'farmersdelight:sweet_berry_cookie');
    event.add('cardboardedition:sellable', 'farmersdelight:honey_cookie');
    event.add('cardboardedition:sellable', 'farmersdelight:melon_popsicle');
    event.add('cardboardedition:sellable', 'farmersdelight:glow_berry_custard');
    event.add('cardboardedition:sellable', 'farmersdelight:fruit_salad');
    event.add('cardboardedition:sellable', 'farmersdelight:mixed_salad');
    event.add('cardboardedition:sellable', 'farmersdelight:nether_salad');
    event.add('cardboardedition:sellable', 'farmersdelight:barbecue_stick');
    event.add('cardboardedition:sellable', 'farmersdelight:egg_sandwich');
    event.add('cardboardedition:sellable', 'farmersdelight:chicken_sandwich');
    event.add('cardboardedition:sellable', 'farmersdelight:hamburger');
    event.add('cardboardedition:sellable', 'farmersdelight:bacon_sandwich');
    event.add('cardboardedition:sellable', 'farmersdelight:mutton_wrap');
    event.add('cardboardedition:sellable', 'farmersdelight:dumplings');
    event.add('cardboardedition:sellable', 'farmersdelight:stuffed_potato');
    event.add('cardboardedition:sellable', 'farmersdelight:cabbage_rolls');
    event.add('cardboardedition:sellable', 'farmersdelight:cod_roll');
    event.add('cardboardedition:sellable', 'farmersdelight:kelp_roll');
    event.add('cardboardedition:sellable', 'farmersdelight:kelp_roll_slice');
    event.add('cardboardedition:sellable', 'farmersdelight:cooked_rice');
    event.add('cardboardedition:sellable', 'farmersdelight:bone_broth');
    event.add('cardboardedition:sellable', 'farmersdelight:beef_stew');
    event.add('cardboardedition:sellable', 'farmersdelight:chicken_soup');
    event.add('cardboardedition:sellable', 'farmersdelight:vegetable_soup');
    event.add('cardboardedition:sellable', 'farmersdelight:fish_stew');
    event.add('cardboardedition:sellable', 'farmersdelight:fried_rice');
    event.add('cardboardedition:sellable', 'farmersdelight:pumpkin_soup');
    event.add('cardboardedition:sellable', 'farmersdelight:baked_cod_stew');
    event.add('cardboardedition:sellable', 'farmersdelight:bacon_and_eggs');
    event.add('cardboardedition:sellable', 'farmersdelight:pasta_with_meatballs');
    event.add('cardboardedition:sellable', 'farmersdelight:pasta_with_mutton_chop');
    event.add('cardboardedition:sellable', 'farmersdelight:mushroom_rice');
    event.add('cardboardedition:sellable', 'farmersdelight:roasted_mutton_chops');
    event.add('cardboardedition:sellable', 'farmersdelight:vegetable_noodles');
    event.add('cardboardedition:sellable', 'farmersdelight:steak_and_potatoes');
    event.add('cardboardedition:sellable', 'farmersdelight:ratatouille');
    event.add('cardboardedition:sellable', 'farmersdelight:squid_ink_pasta');
    event.add('cardboardedition:sellable', 'farmersdelight:grilled_salmon');
    event.add('cardboardedition:sellable', 'farmersdelight:roast_chicken_block');
    event.add('cardboardedition:sellable', 'farmersdelight:stuffed_pumpkin_block');
    event.add('cardboardedition:sellable', 'farmersdelight:honey_glazed_ham_block');
    event.add('cardboardedition:sellable', 'farmersdelight:shepherds_pie_block');
    event.add('cardboardedition:sellable', 'farmersdelight:rice_roll_medley_block');

    event.add('cardboardedition:sellable', 'minecolonies:bell_pepper');
    event.add('cardboardedition:sellable', 'minecolonies:cabbage');
    event.add('cardboardedition:sellable', 'minecolonies:chickpea');
    event.add('cardboardedition:sellable', 'minecolonies:durum');
    event.add('cardboardedition:sellable', 'minecolonies:eggplant');
    event.add('cardboardedition:sellable', 'minecolonies:garlic');
    event.add('cardboardedition:sellable', 'minecolonies:onion');
    event.add('cardboardedition:sellable', 'minecolonies:soybean');
    event.add('cardboardedition:sellable', 'minecolonies:tomato');
    event.add('cardboardedition:sellable', 'minecolonies:rice');
    event.add('cardboardedition:sellable', 'minecolonies:corn');
    event.add('cardboardedition:sellable', 'minecolonies:nether_pepper');
    event.add('cardboardedition:sellable', 'minecolonies:peas');
    event.add('cardboardedition:sellable', 'minecolonies:mint');
    event.add('cardboardedition:sellable', 'minecolonies:butternut_squash');
    event.add('cardboardedition:sellable', 'minecolonies:apple_pie');
    event.add('cardboardedition:sellable', 'minecolonies:baked_salmon');
    event.add('cardboardedition:sellable', 'minecolonies:borscht');
    event.add('cardboardedition:sellable', 'minecolonies:cabochis');
    event.add('cardboardedition:sellable', 'minecolonies:cheddar_cheese');
    event.add('cardboardedition:sellable', 'minecolonies:cheese_pizza');
    event.add('cardboardedition:sellable', 'minecolonies:cheese_ravioli');
    event.add('cardboardedition:sellable', 'minecolonies:chicken_broth');
    event.add('cardboardedition:sellable', 'minecolonies:congee');
    event.add('cardboardedition:sellable', 'minecolonies:cooked_rice');
    event.add('cardboardedition:sellable', 'minecolonies:corn_chowder');
    event.add('cardboardedition:sellable', 'minecolonies:eggdrop_soup');
    event.add('cardboardedition:sellable', 'minecolonies:eggplant_dolma');
    event.add('cardboardedition:sellable', 'minecolonies:feta_cheese');
    event.add('cardboardedition:sellable', 'minecolonies:fish_dinner');
    event.add('cardboardedition:sellable', 'minecolonies:fish_n_chips');
    event.add('cardboardedition:sellable', 'minecolonies:flatbread');
    event.add('cardboardedition:sellable', 'minecolonies:hand_pie');
    event.add('cardboardedition:sellable', 'minecolonies:kebab');
    event.add('cardboardedition:sellable', 'minecolonies:kimchi');
    event.add('cardboardedition:sellable', 'minecolonies:lamb_stew');
    event.add('cardboardedition:sellable', 'minecolonies:lembas_scone');
    event.add('cardboardedition:sellable', 'minecolonies:manchet_bread');
    event.add('cardboardedition:sellable', 'minecolonies:meat_ravioli');
    event.add('cardboardedition:sellable', 'minecolonies:mint_jelly');
    event.add('cardboardedition:sellable', 'minecolonies:mint_tea');
    event.add('cardboardedition:sellable', 'minecolonies:mintchoco_cheesecake');
    event.add('cardboardedition:sellable', 'minecolonies:muffin');
    event.add('cardboardedition:sellable', 'minecolonies:mushroom_pizza');
    event.add('cardboardedition:sellable', 'minecolonies:mutton_dinner');
    event.add('cardboardedition:sellable', 'minecolonies:pasta_plain');
    event.add('cardboardedition:sellable', 'minecolonies:pasta_tomato');
    event.add('cardboardedition:sellable', 'minecolonies:pea_soup');
    event.add('cardboardedition:sellable', 'minecolonies:pepper_hummus');
    event.add('cardboardedition:sellable', 'minecolonies:pierogi');
    event.add('cardboardedition:sellable', 'minecolonies:pita_hummus');
    event.add('cardboardedition:sellable', 'minecolonies:plain_cheesecake');
    event.add('cardboardedition:sellable', 'minecolonies:polenta');
    event.add('cardboardedition:sellable', 'minecolonies:potato_soup');
    event.add('cardboardedition:sellable', 'minecolonies:pottage');
    event.add('cardboardedition:sellable', 'minecolonies:ramen');
    event.add('cardboardedition:sellable', 'minecolonies:rice_ball');
    event.add('cardboardedition:sellable', 'minecolonies:schnitzel');
    event.add('cardboardedition:sellable', 'minecolonies:spicy_eggplant');
    event.add('cardboardedition:sellable', 'minecolonies:spicy_grilled_chicken');
    event.add('cardboardedition:sellable', 'minecolonies:squash_soup');
    event.add('cardboardedition:sellable', 'minecolonies:steak_dinner');
    event.add('cardboardedition:sellable', 'minecolonies:stew_trencher');
    event.add('cardboardedition:sellable', 'minecolonies:stuffed_pepper');
    event.add('cardboardedition:sellable', 'minecolonies:stuffed_pita');
    event.add('cardboardedition:sellable', 'minecolonies:sushi_roll');
    event.add('cardboardedition:sellable', 'minecolonies:tacos');
    event.add('cardboardedition:sellable', 'minecolonies:tofu');
    event.add('cardboardedition:sellable', 'minecolonies:tortillas');
    event.add('cardboardedition:sellable', 'minecolonies:veggie_quiche');
    event.add('cardboardedition:sellable', 'minecolonies:veggie_ravioli');
    event.add('cardboardedition:sellable', 'minecolonies:veggie_soup');
    event.add('cardboardedition:sellable', 'minecolonies:yogurt_with_berries');
})