ItemEvents.modifyTooltips(event => {
	event.add('justdirethings:generatort1', {shift: false}, Text.yellow('Intentionally Disabled'));
    event.add('easy_mob_farm:enduring_capture_net', {shift: false}, Text.yellow('Intentionally Disabled'));
    event.add('easy_mob_farm:ironbound_containment_cage', {shift: false}, Text.yellow('Intentionally Disabled'));
    event.add('easy_mob_farm:void_binding_chain', {shift: false}, Text.yellow('Intentionally Disabled'));
    event.add('easy_mob_farm:mystic_binding_crystal', {shift: false}, Text.yellow('Intentionally Disabled'));

    event.add('sophisticatedstorage:storage_link', {shift: false}, Text.yellow('Intentionally Disabled'));
    event.add('sophisticatedstorage:storage_io', {shift: false}, Text.yellow('Intentionally Disabled'));
    event.add('sophisticatedstorage:storage_input', {shift: false}, Text.yellow('Intentionally Disabled'));
    event.add('sophisticatedstorage:storage_output', {shift: false}, Text.yellow('Intentionally Disabled'));

    event.add('createaddition:rolling_mill', {shift: false}, Text.yellow('Sheet -> Wire, Ingot -> Rods'));
    event.add('createaddition:electrum_ingot', {shift: false}, Text.yellow('Electrified Gold Ingot'));


    event.add('cobblemon:azure_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:beast_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:cherish_ball', {shift: false}, Text.yellow('Sell 4 for 3 Emeralds'));
    event.add('cobblemon:citrine_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:dive_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:dream_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:dusk_ball', {shift: false}, Text.yellow('Sell 4 for 3 Emeralds'));
    event.add('cobblemon:fast_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:friend_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:great_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:heal_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:heavy_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:level_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:lure_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:love_ball', {shift: false}, Text.yellow('Sell 4 for 3 Emeralds'));
    event.add('cobblemon:luxury_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:moon_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:nest_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:net_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:park_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:poke_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:premier_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:quick_ball', {shift: false}, Text.yellow('Sell 4 for 3 Emeralds'));
    event.add('cobblemon:repeat_ball', {shift: false}, Text.yellow('Sell 4 for 3 Emeralds'));
    event.add('cobblemon:roseate_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:safari_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:slate_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));
    event.add('cobblemon:sport_ball', {shift: false}, Text.yellow('Sell 4 for 2 Emeralds'));
    event.add('cobblemon:timer_ball', {shift: false}, Text.yellow('Sell 4 for 3 Emeralds'));
    event.add('cobblemon:ultra_ball', {shift: false}, Text.yellow('Sell 4 for 3 Emeralds'));
    event.add('cobblemon:verdant_ball', {shift: false}, Text.yellow('Sell 4 for 1 Emerald'));

    event.add('farmersdelight:beef_patty', {shift: false}, Text.yellow('Sell 8 for 4 Iron Ingots'));
    event.add('farmersdelight:cooked_chicken_cuts', {shift: false}, Text.yellow('Sell 8 for 4 Iron Ingots'));
    event.add('farmersdelight:cooked_bacon', {shift: false}, Text.yellow('Sell 8 for 4 Iron Ingots'));
    event.add('farmersdelight:cooked_cod_slice', {shift: false}, Text.yellow('12 for 8 Copper Ingots'));
    event.add('farmersdelight:cooked_salmon_slice', {shift: false}, Text.yellow('Sell 8 for 6 Zinc Ingots'));
    event.add('farmersdelight:smoked_ham', {shift: false}, Text.yellow('Sell 8 for 4 Iron Ingots'));
    event.add('farmersdelight:cooked_mutton_chops', {shift: false}, Text.yellow('Sell 8 for 4 Iron Ingots'));
    event.add('farmersdelight:apple_pie', {shift: false}, Text.yellow('Sell 1 for 1 Iron Ingot'));
    event.add('farmersdelight:sweet_berry_cheesecake', {shift: false}, Text.yellow('Sell 1 for 1 Iron Ingot'));
    event.add('farmersdelight:chocolate_pie', {shift: false}, Text.yellow('Sell 1 for 1 Iron Ingot'));
    event.add('farmersdelight:sweet_berry_cookie', {shift: false}, Text.yellow('Sell 1 for 1 Iron Nugget'));
    event.add('farmersdelight:honey_cookie', {shift: false}, Text.yellow('Sell 1 for 1 Gold Nugget'));
    event.add('farmersdelight:melon_popsicle', {shift: false}, Text.yellow('Sell 1 for 1 Blue Ice'));
    event.add('farmersdelight:glow_berry_custard', {shift: false}, Text.yellow('Sell 1 for 1 Glowstone Dust'));
    event.add('farmersdelight:fruit_salad', {shift: false}, Text.yellow('Sell 1 for 1 Melon'));
    event.add('farmersdelight:mixed_salad', {shift: false}, Text.yellow('Sell 1 for 1 Shaft'));
    event.add('farmersdelight:nether_salad', {shift: false}, Text.yellow('Sell 1 for 16 Gunpowder'));
    event.add('farmersdelight:barbecue_stick', {shift: false}, Text.yellow('Sell 1 for 1 Iron Ingot'));
    event.add('farmersdelight:egg_sandwich', {shift: false}, Text.yellow('Sell 1 for 1 Zinc Ingot'));
    event.add('farmersdelight:chicken_sandwich', {shift: false}, Text.yellow('Sell 1 for 1 Chicken'));
    event.add('farmersdelight:hamburger', {shift: false}, Text.yellow('Sell 1 for 1 Beef'));
    event.add('farmersdelight:bacon_sandwich', {shift: false}, Text.yellow('Sell 1 for 1 Porkchop'));
    event.add('farmersdelight:mutton_wrap', {shift: false}, Text.yellow('Sell 1 for 1 Mutton'));
    event.add('farmersdelight:dumplings', {shift: false}, Text.yellow('Sell 2 for 1 Copper Ingot'));
    event.add('farmersdelight:stuffed_potato', {shift: false}, Text.yellow('Sell 1 for 1 Copper Ingot'));
    event.add('farmersdelight:cabbage_rolls', {shift: false}, Text.yellow('Sell 4 for 1 Iron Ingot'));
    event.add('farmersdelight:cod_roll', {shift: false}, Text.yellow('Sell 2 for 8 Copper Ingots'));
    event.add('farmersdelight:kelp_roll', {shift: false}, Text.yellow('Sell 1 for 1 Cod'));
    event.add('farmersdelight:kelp_roll_slice', {shift: false}, Text.yellow('Sell 1 for 1 Iron Nugget'));
    event.add('farmersdelight:cooked_rice', {shift: false}, Text.yellow('Sell 1 for 1 Rice Panicle'));
    event.add('farmersdelight:bone_broth', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:beef_stew', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:chicken_soup', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:vegetable_soup', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:fish_stew', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:fried_rice', {shift: false}, Text.yellow('Sell 4 for 1 Basket'));
    event.add('farmersdelight:pumpkin_soup', {shift: false}, Text.yellow('Sell 1 for 1 Pumpkin'));
    event.add('farmersdelight:baked_cod_stew', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:bacon_and_eggs', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:pasta_with_meatballs', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:pasta_with_mutton_chop', {shift: false}, Text.yellow('Sell 1 for 1 Emerald'));
    event.add('farmersdelight:mushroom_rice', {shift: false}, Text.yellow('Sell 1 for 1 Vertical Gearbox'));
    event.add('farmersdelight:roasted_mutton_chops', {shift: false}, Text.yellow('Sell 1 for 1 Vertical Gearbox'));
    event.add('farmersdelight:vegetable_noodles', {shift: false}, Text.yellow('Sell 1 for 1 Large Cogwheel'));
    event.add('farmersdelight:steak_and_potatoes', {shift: false}, Text.yellow('Sell 1 for 1 Gearbox'));
    event.add('farmersdelight:ratatouille', {shift: false}, Text.yellow('Sell 1 for 1 Cogwheel'));
    event.add('farmersdelight:squid_ink_pasta', {shift: false}, Text.yellow('1 for 4 Ink Sacs'));
    event.add('farmersdelight:grilled_salmon', {shift: false}, Text.yellow('Sell 1 for 1 Propeller'));
    event.add('farmersdelight:roast_chicken_block', {shift: false}, Text.yellow('Sell 1 for 1 Whisk'));
    event.add('farmersdelight:stuffed_pumpkin_block', {shift: false}, Text.yellow('Sell 1 for 1 Brass Block'));
    event.add('farmersdelight:honey_glazed_ham_block', {shift: false}, Text.yellow('Sell 1 for 1 Mechanical Drill'));
    event.add('farmersdelight:shepherds_pie_block', {shift: false}, Text.yellow('Sell 1 for 1 Gearshift'));
    event.add('farmersdelight:rice_roll_medley_block', {shift: false}, Text.yellow('Sell 1 for 1 Encased Chain Drive'));

    event.add('minecolonies:bell_pepper', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:cabbage', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:chickpea', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:durum', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:eggplant', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:garlic', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:onion', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:soybean', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:tomato', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:rice', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:corn', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:nether_pepper', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:peas', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:mint', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:butternut_squash', {shift: false}, Text.yellow('Sell 8 for 1 Emerald'));
    event.add('minecolonies:apple_pie', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:baked_salmon', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:borscht', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:cabochis', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:cheddar_cheese', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:cheese_pizza', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:cheese_ravioli', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:chicken_broth', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:congee', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:cooked_rice', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:corn_chowder', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:eggdrop_soup', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:eggplant_dolma', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:feta_cheese', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:fish_dinner', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:fish_n_chips', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:flatbread', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:hand_pie', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:kebab', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:kimchi', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:lamb_stew', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:lembas_scone', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:manchet_bread', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:meat_ravioli', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:mint_jelly', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:mint_tea', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:mintchoco_cheesecake', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:muffin', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:mushroom_pizza', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:mutton_dinner', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:pasta_plain', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:pasta_tomato', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:pea_soup', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:pepper_hummus', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:pierogi', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:pita_hummus', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:plain_cheesecake', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:polenta', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:potato_soup', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:pottage', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:ramen', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:rice_ball', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:schnitzel', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:spicy_eggplant', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:spicy_grilled_chicken', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:squash_soup', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:steak_dinner', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:stew_trencher', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:stuffed_pepper', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:stuffed_pita', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:sushi_roll', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:tacos', {shift: false}, Text.yellow('Sell for 8 Emeralds'));
    event.add('minecolonies:tofu', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:tortillas', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:veggie_quiche', {shift: false}, Text.yellow('Sell for 2 Emeralds'));
    event.add('minecolonies:veggie_ravioli', {shift: false}, Text.yellow('Sell for 1 Emerald'));
    event.add('minecolonies:veggie_soup', {shift: false}, Text.yellow('Sell for 3 Emeralds'));
    event.add('minecolonies:yogurt_with_berries', {shift: false}, Text.yellow('Sell for 1 Emerald'));
})